# Generated by Django 4.2 on 2023-05-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='email',
            new_name='user',
        ),
    ]
