# Generated by Django 4.2 on 2023-05-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_summary_description_summary_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='user',
            new_name='user_id',
        ),
    ]
